cache:
  - apt
addons:
  apt:
    packages:
    - texlive-full
    - dvipng
    - hunspell

script:
  - hunspell -w -l -t -p custom.dict  "Gautam Kumar Effective Continuous Integration in content_v1.tex"  | grep . && return 1 || return 0
  - mkdir _build
  - pdflatex -halt-on-error -output-directory _build "Gautam Kumar Effective Continuous Integration in content_v1.tex"
